# Generated by Django 2.2.7 on 2019-12-08 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=21)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_toppings', models.IntegerField(default=0)),
                ('topping_included', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Toplink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_toplink', to='orders.Product')),
                ('topping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=models.SET('Product was not found'), related_name='products_orders', to='orders.Product')),
                ('toplink_id', models.ForeignKey(on_delete=models.SET('Topping was not found'), related_name='toplinks', to='orders.Toplink')),
                ('user_id', models.ForeignKey(on_delete=models.SET('User was not found'), related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
