# Generated by Django 2.2.7 on 2019-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='topping_included',
        ),
        migrations.AddField(
            model_name='topping',
            name='type',
            field=models.CharField(default='pizza', max_length=21),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
