# Generated by Django 2.2.7 on 2019-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191208_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_id',
            new_name='order_number',
        ),
        migrations.AlterField(
            model_name='product',
            name='max_toppings',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large')], max_length=21),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Regular Pizza', 'Regular Pizza'), ('Sicilian Pizza', 'Sicilian Pizza'), ('Subs', 'Subs'), ('Pasta', 'Pasta'), ('Salad', 'Salad'), ('Dinner Platters', 'Dinner Platters')], max_length=64),
        ),
        migrations.AlterField(
            model_name='toplink',
            name='product_id',
            field=models.OneToOneField(on_delete=models.SET('Product was not found'), related_name='products_toplink', to='orders.Product'),
        ),
        migrations.RemoveField(
            model_name='toplink',
            name='topping_id',
        ),
        migrations.AddField(
            model_name='toplink',
            name='topping_id',
            field=models.ManyToManyField(related_name='toppings', to='orders.Topping'),
        ),
    ]
