# Generated by Django 2.2.7 on 2019-12-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191208_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='toplink_id',
        ),
        migrations.AddField(
            model_name='order',
            name='toppings_selected',
            field=models.ManyToManyField(related_name='toppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='topping',
            name='products_available',
            field=models.ManyToManyField(related_name='products', to='orders.Product'),
        ),
        migrations.DeleteModel(
            name='Toplink',
        ),
    ]
