# Generated by Django 2.2.7 on 2019-12-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191208_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_toppings',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('undefined', '---'), ('small', 'small'), ('large', 'large')], max_length=21),
        ),
    ]
